var video_details = {
	"appleArchitecture" : { "id" : "appleArchitecture",
		"source" : "https://player.vimeo.com/video/129627076",
		"linkTo" : "https://vimeo.com/125950161",
		"description" : "Architecture 5K iMac - Apple"},
	"duracell" : { "id" : "duracell",
		"source" : "https://player.vimeo.com/video/125950161",
		"linkTo" : "https://vimeo.com/125950161",
		"description" : "Journey to El Capitan - Duracell"},
	"earthPowered" : { "id" : "earthPowered",
		"source" : "https://player.vimeo.com/video/125647792",
		"linkTo" : "https://vimeo.com/125647792",
		"description" : "Earth Powered - Vivint Solar"},
	"cronkitesShambala" : { "id" : "cronkitesShambala",
		"source" : "https://player.vimeo.com/video/127563974",
		"linkTo" : "https://vimeo.com/127563974",
		"description" : "The Cronkites - MP Cunningham"},
	"prime" : { "id" : "prime",
		"source" : "https://www.youtube.com/embed/fI4hdJnpMdc",
		"linkTo" : "https://www.youtube.com/embed/fI4hdJnpMdc",
		"description" : "There There - Amazon Prime (DE)"},
	"orcaHealth" : { "id" : "orcaHealth",
		"source" : "https://player.vimeo.com/video/76189894",
		"linkTo" : "https://vimeo.com/76189894",
		"description" : "Orca Health"},
	"uefa" : { "id" : "uefa",
		"source" : "https://www.youtube.com/embed/iTeNictJxMw",
		"linkTo" : "https://www.youtube.com/embed/iTeNictJxMw",
		"description" : "Respect - UEFA"},
	"observer" : { "id" : "observer",
		"source" : "https://player.vimeo.com/video/99895335",
		"linkTo" : "https://vimeo.com/99895335",
		"description" : "The Observer - MP Cunningham"},
	"superMillie" : { "id" : "superMillie",
		"source" : "https://player.vimeo.com/video/89952173",
		"linkTo" : "https://vimeo.com/89952173",
		"description" : "Super Millie - Vivint Solar"},	
	"nightClimbing" : { "id" : "nightClimbing",
		"source" : "https://player.vimeo.com/video/125956151",
		"linkTo" : "https://vimeo.com/125956151",
		"description" : "Night Climbing - Duracell"},
	"caleb" : { "id" : "caleb",
		"source" : "https://player.vimeo.com/video/79275401",
		"linkTo" : "hhttps://vimeo.com/79275401",
		"description" : "Caleb - Vivint Solar"},
	"general" : { "id" : "general",
		"source" : "https://player.vimeo.com/video/70799925",
		"linkTo" : "https://vimeo.com/70799925",
		"description" : "The General - MP Cunningham"},


};

