var video_details = [
	{ "videoId" : "appleArchitecture",
		"vidSource" : "https://player.vimeo.com/video/129627076",
		"linkTo" : "https://vimeo.com/125950161",
		"description" : "Architecture 5K iMac - Apple"},
	{ "videoId" : "duracell",
		"vidSource" : "https://player.vimeo.com/video/125950161",
		"linkTo" : "https://vimeo.com/125950161",
		"description" : "Journey to El Capitan - Duracell"},
	{ "videoId" : "earthPowered",
		"vidSource" : "https://player.vimeo.com/video/125647792",
		"linkTo" : "https://vimeo.com/125647792",
		"description" : "Earth Powered - Vivint Solar"},
	{ "videoId" : "cronkitesShambala",
		"vidSource" : "https://player.vimeo.com/video/127563974",
		"linkTo" : "https://vimeo.com/127563974",
		"description" : "The Cronkites - MP Cunningham"},
	{ "videoId" : "prime",
		"vidSource" : "https://www.youtube.com/embed/fI4hdJnpMdc",
		"linkTo" : "https://www.youtube.com/embed/fI4hdJnpMdc",
		"description" : "There There - Amazon Prime (DE)"},
	{ "videoId" : "orcaHealth",
		"vidSource" : "https://player.vimeo.com/video/76189894",
		"linkTo" : "https://vimeo.com/76189894",
		"description" : "Orca Health"},
	{ "videoId" : "uefa",
		"vidSource" : "https://www.youtube.com/embed/iTeNictJxMw",
		"linkTo" : "https://www.youtube.com/embed/iTeNictJxMw",
		"description" : "Respect - UEFA"},
	{ "videoId" : "observer",
		"vidSource" : "https://player.vimeo.com/video/99895335",
		"linkTo" : "https://vimeo.com/99895335",
		"description" : "The Observer - MP Cunningham"},
	{ "videoId" : "superMillie",
		"vidSource" : "https://player.vimeo.com/video/89952173",
		"linkTo" : "https://vimeo.com/89952173",
		"description" : "Super Millie - Vivint Solar"},	
	{ "videoId" : "nightClimbing",
		"vidSource" : "https://player.vimeo.com/video/125956151",
		"linkTo" : "https://vimeo.com/125956151",
		"description" : "Night Climbing - Duracell"},
	{ "videoId" : "caleb",
		"vidSource" : "https://player.vimeo.com/video/79275401",
		"linkTo" : "hhttps://vimeo.com/79275401",
		"description" : "Caleb - Vivint Solar"},
	{ "videoId" : "general",
		"vidSource" : "https://player.vimeo.com/video/70799925",
		"linkTo" : "https://vimeo.com/70799925",
		"description" : "The General - MP Cunningham"},
];